import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/About.module.css'
import NavBar from '@/Components/navbar'
import AboutMe from '@/Components/aboutme'
import Footer from '@/Components/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Navid Memari</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar />
        <AboutMe 
          img='/../public/DSC03141-min.jpg'
          title='🎤 *tap* *tap* Is this thing on?'
          description1='👋 Hello! I’m Navid. I’m currently studying Digital Design and Development at BCIT. I have a strong passion for graphic design and web development with a great interest in the field of UI/UX. I’ve developed experience in asset creation, layout design and development, and user experience research and design. I am proficient in using Adobe Creative Cloud and Figma for graphic design and UI/UX. I am also proficient in using HTML5, CSS, and Javascript and have developed a variety of responsive web pages.' 
          description2='I love design, and exploring different methods and styles to create something pleasing to the eyes. I enjoy solving problems creatively and efficiently using modern solutions. I love to stay updated on the latest tech releases and innovations in the design industry. I’m adaptive and detail-oriented, and I often find myself to be an extrovert thinker in a team environment as I love bouncing around ideas and compromising to come up with the best solution.' 
          description3='In my spare time I often like to 💪workout at the gym, 📖read manga and 🎮play video games. When I find the right motivation I love to develop my skills in other software and programming languages. This year I have been learning game development using the Godot engine and C#. My favourite genre of media is horror as I find that it’s very hard to make successfully, and I have tremendous respect for authors and directors that do make enjoyable horror media.'
        />
        <Footer />
      </main>
    </>
  )
}
