import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/Components/navbar'
import Welcome from '@/Components/welcome'
import ProjectRight from '@/Components/projectRight'
import ProjectLeft from '@/Components/projectLeft'
import Footer from '@/Components/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Navid Memari</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar />
        <Welcome img = '/../public/down-arrow-56.png'/>
        <div id='project'>
          <div className={styles.featured}>Featured Projects</div>
          <ProjectRight 
            img='/../public/Void.png'
            title='Void: A Personalized Mental Health Mobile App'
            description='In an effort to practice user experience, our team created an app called 
            Void. This app mainly serves as a personalized mental health app where the user can conduct 
            certain activities such as box breathing and journaling. The development process of Void 
            included user research through a survey and interviews, a low fidelity prototype, a mid-fidelity prototype, 
            and a high fidelity prototype. All the prototyping was done through figma.'
          />
          <ProjectLeft 
            img='/../public/Boxterra.png'
            title='Boxterra E-Commerce Website'
            description='Boxterra is a hypothetical company that sells customizable or pre-made 
            terrariums online on their company website. Our team designed the website using style 
            guide, and the layout was designed and prototyped using Figma.'
          />
        </div>
        <Footer />
      </main>
    </>
  )
}
